export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAIL = 'GET_JOBS_FAIL';

export const GET_JOB_DETAILS_REQUEST = 'GET_JOB_DETAILS_REQUEST';
export const GET_JOB_DETAILS_SUCCESS = 'GET_JOB_DETAILS_SUCCESS';
export const GET_JOB_DETAILS_FAIL = 'GET_JOB_DETAILS_FAIL';

export const GET_SAVED_JOBS_REQUEST = 'GET_SAVED_JOBS_REQUEST';
export const GET_SAVED_JOBS_SUCCESS = 'GET_SAVED_JOBS_SUCCESS';
export const GET_SAVED_JOBS_FAIL = 'GET_SAVED_JOBS_FAIL';

export const SAVE_JOB_REQUEST = 'SAVE_JOB_REQUEST';
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCCESS';
export const SAVE_JOB_FAIL = 'SAVE_JOB_FAIL';
